name: Cargo Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo_build_and_test:
    name: Cargo Build and Test

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Cargo Build
      run: cargo build --verbose
    - name: Cargo Test
      run: cargo test --verbose
